### ISSUE TITLE
TTL=None doesn`t do what docs say

### ISSUE THREAD

**Issue by paulo-raca** [1stvamp/memorised#17]
I just noticed, the docs say that setting TTL to `None` should disable caching, but instead it calls memcache's `set` with the default TTL, which is 0 / infinite.
https://github.com/1stvamp/memorised/blob/master/memorised/decorators.py#L197
https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L641

What should we fix, the docs or the code?

**Comment by 1stvamp** [comment]
Seems fixed with your latest commits merged: https://github.com/1stvamp/memorised/blob/master/memorised/decorators.py#L215

btw @paulo-raca I hope you don't mind my adding you to project contributors on the repo, I don't get to do anything with this lib much these days and your PRs have been great.

**Comment by paulo-raca** [comment]
Thanks for adding me, I'm glad my contributions have been appreciated.

about the `ttl=None`, my change doesn

**Comment by 1stvamp** [comment]
Yeah I saee what you mean. I think it's worth keeping the functionality to be able to disable caching by setting None (with 0 being always cache, as that maps directly to the python-memcache behaviour).
So I'm thinking https://github.com/1stvamp/memorised/blob/master/memorised/decorators.py#L116 needs to check if ttl is None or not (otherwise falling over to the same functinality as if a backend cache isn't available).
